import React from 'react';
import '../App.css';
import './paciente.css';
import { Link } from 'react-router-dom/dist';

function PacientesPage() {
  const patients = 
  [
    {
      "nome": "Antonio José Cardoso",
      "idade": 25,
      "cpf": "613.146.814-19",
      "rg": "12.451.754-7",
      "data_nasc": "15/05/1999",
      "sexo": "Masculino",
      "signo": "Touro",
      "mae": "Josefa Sabrina Beatriz",
      "pai": "Joaquim Cauê Cardoso",
      "email": "antoniojosecardoso@ocaconsultoria.com",
      "senha": "2JTzzBuYQ7",
      "cep": "77420-350",
      "endereco": "Rua 4",
      "numero": 798,
      "bairro": "Parque Residencial Nova Fronteira",
      "cidade": "Gurupi",
      "estado": "TO",
      "telefone_fixo": "(63) 2654-1090",
      "celular": "(63) 99107-1559",
      "altura": "1,75",
      "peso": 97,
      "tipo_sanguineo": "B+",
      "cor": "verde"
    },
    {
      "nome": "Luan Anthony Elias Pinto",
      "idade": 69,
      "cpf": "982.809.928-47",
      "rg": "45.263.679-6",
      "data_nasc": "17/03/1955",
      "sexo": "Masculino",
      "signo": "Peixes",
      "mae": "Luana Mariana",
      "pai": "Elias Miguel Pinto",
      "email": "luan-pinto78@amoreencantos.com",
      "senha": "H3GHNQO7Qq",
      "cep": "69101-348",
      "endereco": "Rua 1",
      "numero": 929,
      "bairro": "Prainha",
      "cidade": "Itacoatiara",
      "estado": "AM",
      "telefone_fixo": "(92) 3871-2906",
      "celular": "(92) 99790-2603",
      "altura": "1,89",
      "peso": 96,
      "tipo_sanguineo": "O-",
      "cor": "vermelho"
    },
    {
      "nome": "Malu Emanuelly Melissa da Mata",
      "idade": 31,
      "cpf": "447.508.082-70",
      "rg": "11.078.309-8",
      "data_nasc": "09/01/1993",
      "sexo": "Feminino",
      "signo": "Capricórnio",
      "mae": "Emily Luciana Eloá",
      "pai": "Thiago Enrico da Mata",
      "email": "malu-damata96@yahoo.se",
      "senha": "9KWtmUM8Pr",
      "cep": "88348-589",
      "endereco": "Rua Monte Stanley",
      "numero": 419,
      "bairro": "Monte Alegre (Monte Alegre)",
      "cidade": "Camboriú",
      "estado": "SC",
      "telefone_fixo": "(47) 2627-7365",
      "celular": "(47) 99468-9098",
      "altura": "1,67",
      "peso": 58,
      "tipo_sanguineo": "A+",
      "cor": "preto"
    },
    {
      "nome": "Alexandre Fábio Novaes",
      "idade": 31,
      "cpf": "574.960.385-71",
      "rg": "32.583.022-8",
      "data_nasc": "18/01/1993",
      "sexo": "Masculino",
      "signo": "Capricórnio",
      "mae": "Isabel Antônia",
      "pai": "Leonardo Caio Samuel Novaes",
      "email": "alexandrefabionovaes@4now.com.br",
      "senha": "w5AGNRocg2",
      "cep": "38303-016",
      "endereco": "Travessa Rubi",
      "numero": 540,
      "bairro": "Boa Esperança",
      "cidade": "Ituiutaba",
      "estado": "MG",
      "telefone_fixo": "(34) 3536-9446",
      "celular": "(34) 98739-6271",
      "altura": "1,74",
      "peso": 97,
      "tipo_sanguineo": "A-",
      "cor": "amarelo"
    },
    {
      "nome": "Catarina Ayla Alice Nunes",
      "idade": 65,
      "cpf": "196.560.859-06",
      "rg": "34.832.420-0",
      "data_nasc": "18/06/1959",
      "sexo": "Feminino",
      "signo": "Gêmeos",
      "mae": "Allana Gabrielly",
      "pai": "Vitor Emanuel Nunes",
      "email": "catarina_ayla_nunes@sebrace.com.br",
      "senha": "dCDoSYrqdJ",
      "cep": "79108-100",
      "endereco": "Rua Luzíadas",
      "numero": 843,
      "bairro": "Núcleo Industrial",
      "cidade": "Campo Grande",
      "estado": "MS",
      "telefone_fixo": "(67) 2657-7979",
      "celular": "(67) 98475-2794",
      "altura": "1,78",
      "peso": 89,
      "tipo_sanguineo": "O+",
      "cor": "verde"
    },
    {
      "nome": "Geraldo Davi Caldeira",
      "idade": 58,
      "cpf": "637.236.181-70",
      "rg": "19.581.332-7",
      "data_nasc": "01/03/1966",
      "sexo": "Masculino",
      "signo": "Peixes",
      "mae": "Tatiane Eloá",
      "pai": "Anthony Ian Caldeira",
      "email": "geraldo_davi_caldeira@edbrasil.net",
      "senha": "InFIpdjZwc",
      "cep": "86191-440",
      "endereco": "Rua Américo Vendramel",
      "numero": 581,
      "bairro": "Jardim Boa Vista",
      "cidade": "Cambé",
      "estado": "PR",
      "telefone_fixo": "(43) 2518-0737",
      "celular": "(43) 99569-6349",
      "altura": "1,84",
      "peso": 82,
      "tipo_sanguineo": "A-",
      "cor": "preto"
    },
    {
      "nome": "Sebastião Raul Figueiredo",
      "idade": 57,
      "cpf": "587.882.819-73",
      "rg": "46.772.356-4",
      "data_nasc": "02/07/1967",
      "sexo": "Masculino",
      "signo": "Câncer",
      "mae": "Nina Alessandra",
      "pai": "Alexandre Yuri Figueiredo",
      "email": "sebastiao_figueiredo@eguia.com.br",
      "senha": "H4P1sKOmKj",
      "cep": "77019-426",
      "endereco": "Quadra 1203 Sul Alameda 20",
      "numero": 131,
      "bairro": "Plano Diretor Sul",
      "cidade": "Palmas",
      "estado": "TO",
      "telefone_fixo": "(63) 2983-0375",
      "celular": "(63) 99902-0499",
      "altura": "1,89",
      "peso": 105,
      "tipo_sanguineo": "O+",
      "cor": "preto"
    },
    {
      "nome": "Luan Bento Raimundo Fernandes",
      "idade": 33,
      "cpf": "126.195.164-63",
      "rg": "49.441.403-0",
      "data_nasc": "04/04/1991",
      "sexo": "Masculino",
      "signo": "Áries",
      "mae": "Tânia Cláudia Marlene",
      "pai": "Luís Rafael Hugo Fernandes",
      "email": "luan_fernandes@grupoprovac.com.br",
      "senha": "8hC2qqyPyW",
      "cep": "33140-100",
      "endereco": "Rua Alberto Rodrigues da Silva",
      "numero": 369,
      "bairro": "Conjunto Palmital (São Benedito)",
      "cidade": "Santa Luzia",
      "estado": "MG",
      "telefone_fixo": "(31) 2525-0589",
      "celular": "(31) 98350-8604",
      "altura": "1,90",
      "peso": 93,
      "tipo_sanguineo": "A-",
      "cor": "vermelho"
    },
    {
      "nome": "Laura Isabelle Bárbara Gomes",
      "idade": 55,
      "cpf": "698.272.297-02",
      "rg": "19.656.419-0",
      "data_nasc": "27/04/1969",
      "sexo": "Feminino",
      "signo": "Touro",
      "mae": "Elisa Maria Fernanda",
      "pai": "Joaquim Leonardo Nathan Gomes",
      "email": "laura_isabelle_gomes@huios.com.br",
      "senha": "LytwJlF5Ww",
      "cep": "29700-565",
      "endereco": "Rodovia BR-259",
      "numero": 223,
      "bairro": "Colatina Velha",
      "cidade": "Colatina",
      "estado": "ES",
      "telefone_fixo": "(27) 3620-6072",
      "celular": "(27) 98566-6193",
      "altura": "1,73",
      "peso": 72,
      "tipo_sanguineo": "A-",
      "cor": "preto"
    },
    {
      "nome": "André Pedro Porto",
      "idade": 64,
      "cpf": "114.587.354-51",
      "rg": "32.537.127-1",
      "data_nasc": "21/04/1960",
      "sexo": "Masculino",
      "signo": "Touro",
      "mae": "Emily Allana",
      "pai": "Ryan Samuel Danilo Porto",
      "email": "andre_porto@parker.com",
      "senha": "EWLHfKPCCB",
      "cep": "49088-455",
      "endereco": "Rua Onze",
      "numero": 397,
      "bairro": "Lamarão",
      "cidade": "Aracaju",
      "estado": "SE",
      "telefone_fixo": "(79) 2522-0422",
      "celular": "(79) 99320-8924",
      "altura": "1,84",
      "peso": 99,
      "tipo_sanguineo": "O+",
      "cor": "verde"
    },
    {
      "nome": "Antonella Isabelly Sales",
      "idade": 60,
      "cpf": "987.284.845-92",
      "rg": "37.959.222-8",
      "data_nasc": "18/05/1964",
      "sexo": "Feminino",
      "signo": "Touro",
      "mae": "Mariane Sara",
      "pai": "Henry Ruan Sales",
      "email": "antonella.isabelly.sales@prohaska.com.br",
      "senha": "kqmJt2zkw6",
      "cep": "77060-330",
      "endereco": "Avenida Goiás",
      "numero": 889,
      "bairro": "Jardim Santa Bárbara",
      "cidade": "Palmas",
      "estado": "TO",
      "telefone_fixo": "(63) 3901-9847",
      "celular": "(63) 99157-0845",
      "altura": "1,78",
      "peso": 63,
      "tipo_sanguineo": "AB+",
      "cor": "amarelo"
    },
    {
      "nome": "Rafael Emanuel Martin Gonçalves",
      "idade": 48,
      "cpf": "789.918.113-53",
      "rg": "25.550.572-3",
      "data_nasc": "02/04/1976",
      "sexo": "Masculino",
      "signo": "Áries",
      "mae": "Marlene Carolina",
      "pai": "Fábio Lucca Gonçalves",
      "email": "rafael.emanuel.goncalves@unifox.com.br",
      "senha": "9xtXuzFco0",
      "cep": "74911-260",
      "endereco": "Rua 27",
      "numero": 296,
      "bairro": "Vila Brasília",
      "cidade": "Aparecida de Goiânia",
      "estado": "GO",
      "telefone_fixo": "(62) 2884-4629",
      "celular": "(62) 99392-6167",
      "altura": "1,67",
      "peso": 63,
      "tipo_sanguineo": "A-",
      "cor": "vermelho"
    },
    {
      "nome": "Alana Jéssica Sarah Ramos",
      "idade": 64,
      "cpf": "622.822.390-91",
      "rg": "32.445.133-7",
      "data_nasc": "13/01/1960",
      "sexo": "Feminino",
      "signo": "Capricórnio",
      "mae": "Cristiane Laura Julia",
      "pai": "Juan Calebe Nicolas Ramos",
      "email": "alana.jessica.ramos@ciaimoveissjc.com",
      "senha": "dMYdqAqyzi",
      "cep": "74810-909",
      "endereco": "Rua Castorina Bittencourt Alves 349 Quadra C-20 Lote 1E",
      "numero": 214,
      "bairro": "Jardim Goiás",
      "cidade": "Goiânia",
      "estado": "GO",
      "telefone_fixo": "(62) 3586-4937",
      "celular": "(62) 99642-0830",
      "altura": "1,56",
      "peso": 66,
      "tipo_sanguineo": "B+",
      "cor": "azul"
    },
    {
      "nome": "Natália Aparecida Julia Nogueira",
      "idade": 40,
      "cpf": "308.439.173-42",
      "rg": "15.834.787-0",
      "data_nasc": "13/06/1984",
      "sexo": "Feminino",
      "signo": "Gêmeos",
      "mae": "Lavínia Esther",
      "pai": "Jorge Kevin Paulo Nogueira",
      "email": "nataliaaparecidanogueira@uou.com.br",
      "senha": "LDJEu5CZCe",
      "cep": "36200-109",
      "endereco": "Rua Aniceto Puiatti",
      "numero": 542,
      "bairro": "Centro",
      "cidade": "Barbacena",
      "estado": "MG",
      "telefone_fixo": "(32) 2858-8752",
      "celular": "(32) 98497-8183",
      "altura": "1,75",
      "peso": 73,
      "tipo_sanguineo": "O+",
      "cor": "preto"
    },
    {
      "nome": "Raimunda Emilly da Rocha",
      "idade": 20,
      "cpf": "922.134.179-89",
      "rg": "34.329.867-3",
      "data_nasc": "15/06/2004",
      "sexo": "Feminino",
      "signo": "Gêmeos",
      "mae": "Lavínia Sara Carla",
      "pai": "Iago Cauã Sérgio da Rocha",
      "email": "raimunda_emilly_darocha@eternalam.com.br",
      "senha": "KhMxZeQxy4",
      "cep": "69093-823",
      "endereco": "Rua Santo Anacleto",
      "numero": 246,
      "bairro": "Monte das Oliveiras",
      "cidade": "Manaus",
      "estado": "AM",
      "telefone_fixo": "(92) 2807-9610",
      "celular": "(92) 98126-9156",
      "altura": "1,51",
      "peso": 60,
      "tipo_sanguineo": "A-",
      "cor": "roxo"
    },
    {
      "nome": "José Vitor Souza",
      "idade": 24,
      "cpf": "064.727.159-12",
      "rg": "43.954.653-9",
      "data_nasc": "26/01/2000",
      "sexo": "Masculino",
      "signo": "Aquário",
      "mae": "Lívia Liz Mirella",
      "pai": "Roberto Carlos Souza",
      "email": "jose_souza@mmarques.com",
      "senha": "9ZDAMD99mp",
      "cep": "30360-450",
      "endereco": "Rua Plutão",
      "numero": 379,
      "bairro": "Santa Lúcia",
      "cidade": "Belo Horizonte",
      "estado": "MG",
      "telefone_fixo": "(31) 2903-3974",
      "celular": "(31) 99606-9480",
      "altura": "1,73",
      "peso": 82,
      "tipo_sanguineo": "AB-",
      "cor": "preto"
    },
    {
      "nome": "João Paulo Murilo Corte Real",
      "idade": 59,
      "cpf": "854.672.650-75",
      "rg": "26.132.095-6",
      "data_nasc": "17/04/1965",
      "sexo": "Masculino",
      "signo": "Áries",
      "mae": "Maria Sara Regina",
      "pai": "José Benjamin Noah Corte Real",
      "email": "joao.paulo.cortereal@lojasrayton.com",
      "senha": "UpB4p0JBg2",
      "cep": "92441-100",
      "endereco": "Rua Olímpio Ferreira Cruz",
      "numero": 667,
      "bairro": "Guajuviras",
      "cidade": "Canoas",
      "estado": "RS",
      "telefone_fixo": "(51) 2612-8058",
      "celular": "(51) 99146-6098",
      "altura": "2,00",
      "peso": 106,
      "tipo_sanguineo": "O+",
      "cor": "verde"
    },
    {
      "nome": "Hugo Renato Nascimento",
      "idade": 34,
      "cpf": "053.829.196-66",
      "rg": "24.905.648-3",
      "data_nasc": "09/01/1990",
      "sexo": "Masculino",
      "signo": "Capricórnio",
      "mae": "Beatriz Luzia Eloá",
      "pai": "Cauê Theo Nascimento",
      "email": "hugo_nascimento@tirel.com.br",
      "senha": "a7zzPdWtBb",
      "cep": "86801-407",
      "endereco": "Travessa Borrazópolis",
      "numero": 219,
      "bairro": "Núcleo Habitacional Nossa Senhora Aparecida",
      "cidade": "Apucarana",
      "estado": "PR",
      "telefone_fixo": "(43) 2817-0035",
      "celular": "(43) 99360-3859",
      "altura": "1,88",
      "peso": 78,
      "tipo_sanguineo": "B+",
      "cor": "vermelho"
    },
    {
      "nome": "Beatriz Alana Daniela da Rosa",
      "idade": 39,
      "cpf": "982.258.614-00",
      "rg": "25.659.593-8",
      "data_nasc": "02/07/1985",
      "sexo": "Feminino",
      "signo": "Câncer",
      "mae": "Fernanda Isabela Laura",
      "pai": "Marcos Vinicius Rodrigo da Rosa",
      "email": "beatrizalanadarosa@jotace.eti.br",
      "senha": "ad0inlPl0X",
      "cep": "59078-550",
      "endereco": "Rua Pedro Vilela Cid",
      "numero": 766,
      "bairro": "Capim Macio",
      "cidade": "Natal",
      "estado": "RN",
      "telefone_fixo": "(84) 2910-7038",
      "celular": "(84) 98654-7249",
      "altura": "1,66",
      "peso": 61,
      "tipo_sanguineo": "B-",
      "cor": "vermelho"
    },
    {
      "nome": "Tomás Ruan Freitas",
      "idade": 29,
      "cpf": "597.728.641-42",
      "rg": "50.300.449-2",
      "data_nasc": "14/05/1995",
      "sexo": "Masculino",
      "signo": "Touro",
      "mae": "Natália Elisa Isabelle",
      "pai": "Thiago Rodrigo Alexandre Freitas",
      "email": "tomas.ruan.freitas@numero.com.br",
      "senha": "di6pJ7i4rK",
      "cep": "76871-250",
      "endereco": "Rua Matão",
      "numero": 618,
      "bairro": "Jardim Paulista",
      "cidade": "Ariquemes",
      "estado": "RO",
      "telefone_fixo": "(69) 3988-0730",
      "celular": "(69) 99144-4696",
      "altura": "1,73",
      "peso": 100,
      "tipo_sanguineo": "O-",
      "cor": "amarelo"
    },
    {
      "nome": "Vicente Otávio Almeida",
      "idade": 64,
      "cpf": "031.745.177-45",
      "rg": "39.895.738-1",
      "data_nasc": "04/03/1960",
      "sexo": "Masculino",
      "signo": "Peixes",
      "mae": "Jéssica Lívia Alessandra",
      "pai": "Benício Geraldo Almeida",
      "email": "vicente_almeida@lphbrasil.com.br",
      "senha": "Bsj3jngjfx",
      "cep": "79815-307",
      "endereco": "Rua Ouro Preto",
      "numero": 354,
      "bairro": "Chácaras Trevo",
      "cidade": "Dourados",
      "estado": "MS",
      "telefone_fixo": "(67) 2870-2869",
      "celular": "(67) 98511-9453",
      "altura": "1,63",
      "peso": 79,
      "tipo_sanguineo": "O+",
      "cor": "vermelho"
    },
    {
      "nome": "César Ian Galvão",
      "idade": 80,
      "cpf": "067.700.215-79",
      "rg": "27.226.898-7",
      "data_nasc": "02/03/1944",
      "sexo": "Masculino",
      "signo": "Peixes",
      "mae": "Yasmin Beatriz Elisa",
      "pai": "César Tiago Enrico Galvão",
      "email": "cesar_ian_galvao@fanger.com.br",
      "senha": "8axHdoIo5D",
      "cep": "64034-624",
      "endereco": "Rua Professor Eduardo Santana",
      "numero": 174,
      "bairro": "Angelim",
      "cidade": "Teresina",
      "estado": "PI",
      "telefone_fixo": "(86) 2541-4580",
      "celular": "(86) 99948-6214",
      "altura": "1,66",
      "peso": 68,
      "tipo_sanguineo": "B+",
      "cor": "vermelho"
    },
    {
      "nome": "Gabriela Sara Ferreira",
      "idade": 41,
      "cpf": "116.837.756-00",
      "rg": "26.015.797-1",
      "data_nasc": "02/07/1983",
      "sexo": "Feminino",
      "signo": "Câncer",
      "mae": "Isabela Andrea",
      "pai": "Cauê Calebe Marcelo Ferreira",
      "email": "gabriela_ferreira@redacaofinal.com.br",
      "senha": "PWnyrJLdOh",
      "cep": "78734-520",
      "endereco": "Rua Catorze",
      "numero": 418,
      "bairro": "Residencial Sítio Farias",
      "cidade": "Rondonópolis",
      "estado": "MT",
      "telefone_fixo": "(66) 2641-0906",
      "celular": "(66) 99382-3173",
      "altura": "1,68",
      "peso": 76,
      "tipo_sanguineo": "O+",
      "cor": "preto"
    },
    {
      "nome": "Liz Sueli Mirella Fogaça",
      "idade": 52,
      "cpf": "829.869.432-50",
      "rg": "20.918.432-2",
      "data_nasc": "21/06/1972",
      "sexo": "Feminino",
      "signo": "Câncer",
      "mae": "Betina Cristiane Juliana",
      "pai": "Kauê Rafael Fogaça",
      "email": "liz-fogaca83@agenziamarketing.com.br",
      "senha": "OHyj3n4YS9",
      "cep": "91420-752",
      "endereco": "Beco Três",
      "numero": 519,
      "bairro": "Bom Jesus",
      "cidade": "Porto Alegre",
      "estado": "RS",
      "telefone_fixo": "(51) 3776-0904",
      "celular": "(51) 99231-2468",
      "altura": "1,59",
      "peso": 53,
      "tipo_sanguineo": "O-",
      "cor": "amarelo"
    },
    {
      "nome": "Julio Manoel Luiz da Paz",
      "idade": 78,
      "cpf": "008.932.731-47",
      "rg": "14.993.822-6",
      "data_nasc": "24/05/1946",
      "sexo": "Masculino",
      "signo": "Gêmeos",
      "mae": "Allana Rayssa Rosângela",
      "pai": "Joaquim Benício da Paz",
      "email": "julio_dapaz@microdoc.com.br",
      "senha": "gszLtJXfwJ",
      "cep": "32673-820",
      "endereco": "Via Expressa",
      "numero": 753,
      "bairro": "Duque de Caxias",
      "cidade": "Betim",
      "estado": "MG",
      "telefone_fixo": "(31) 2530-7802",
      "celular": "(31) 98310-3004",
      "altura": "1,92",
      "peso": 69,
      "tipo_sanguineo": "A+",
      "cor": "preto"
    },
    {
      "nome": "Gael Pedro Henrique Edson Barros",
      "idade": 74,
      "cpf": "996.103.008-71",
      "rg": "10.537.064-2",
      "data_nasc": "02/07/1950",
      "sexo": "Masculino",
      "signo": "Câncer",
      "mae": "Cecília Marcela",
      "pai": "Marcelo Fábio Barros",
      "email": "gael_barros@yaooll.com",
      "senha": "DffDpcC9s9",
      "cep": "69313-152",
      "endereco": "Rua Manoel Pereira de Castro",
      "numero": 788,
      "bairro": "Jóquei Clube",
      "cidade": "Boa Vista",
      "estado": "RR",
      "telefone_fixo": "(95) 3618-9052",
      "celular": "(95) 99245-3034",
      "altura": "1,62",
      "peso": 56,
      "tipo_sanguineo": "B-",
      "cor": "azul"
    },
    {
      "nome": "Márcia Priscila Pietra Barbosa",
      "idade": 64,
      "cpf": "957.500.606-24",
      "rg": "18.414.753-0",
      "data_nasc": "08/01/1960",
      "sexo": "Feminino",
      "signo": "Capricórnio",
      "mae": "Clara Márcia",
      "pai": "Martin Theo Martin Barbosa",
      "email": "marcia_barbosa@atiara.com.br",
      "senha": "Kr2nlIjNDy",
      "cep": "74474-209",
      "endereco": "Rua VB 6",
      "numero": 495,
      "bairro": "Jardim Vista Bela",
      "cidade": "Goiânia",
      "estado": "GO",
      "telefone_fixo": "(62) 3907-3857",
      "celular": "(62) 98967-8663",
      "altura": "1,66",
      "peso": 84,
      "tipo_sanguineo": "B+",
      "cor": "verde"
    },
    {
      "nome": "Bruna Caroline Isis da Conceição",
      "idade": 76,
      "cpf": "418.801.328-18",
      "rg": "46.751.014-3",
      "data_nasc": "25/06/1948",
      "sexo": "Feminino",
      "signo": "Câncer",
      "mae": "Antônia Priscila",
      "pai": "Benício Iago da Conceição",
      "email": "brunacarolinedaconceicao@trt15.jus.br",
      "senha": "9PdeBZEDpE",
      "cep": "59615-380",
      "endereco": "Rua José Estácio Damião",
      "numero": 908,
      "bairro": "Santa Delmira",
      "cidade": "Mossoró",
      "estado": "RN",
      "telefone_fixo": "(84) 3890-0812",
      "celular": "(84) 99895-1926",
      "altura": "1,71",
      "peso": 71,
      "tipo_sanguineo": "O-",
      "cor": "verde"
    },
    {
      "nome": "Otávio Juan Bernardes",
      "idade": 48,
      "cpf": "238.507.940-24",
      "rg": "30.194.978-5",
      "data_nasc": "10/03/1976",
      "sexo": "Masculino",
      "signo": "Peixes",
      "mae": "Sandra Kamilly Débora",
      "pai": "Nicolas Victor Thiago Bernardes",
      "email": "otavio_juan_bernardes@me.com.br",
      "senha": "afgYjnJcTx",
      "cep": "88308-335",
      "endereco": "Rua Pantaleão Francisco Casas",
      "numero": 542,
      "bairro": "Cidade Nova",
      "cidade": "Itajaí",
      "estado": "SC",
      "telefone_fixo": "(47) 2848-4965",
      "celular": "(47) 98852-8002",
      "altura": "1,94",
      "peso": 84,
      "tipo_sanguineo": "B+",
      "cor": "amarelo"
    },
    {
      "nome": "Theo Bento Drumond",
      "idade": 49,
      "cpf": "487.785.777-05",
      "rg": "18.056.379-8",
      "data_nasc": "02/07/1975",
      "sexo": "Masculino",
      "signo": "Câncer",
      "mae": "Camila Ayla",
      "pai": "Lucca Erick Iago Drumond",
      "email": "theo_bento_drumond@hotmai.com",
      "senha": "uacsag1Xcx",
      "cep": "89260-483",
      "endereco": "Servidão Alfonso Karstens",
      "numero": 158,
      "bairro": "Barra do Rio Cerro",
      "cidade": "Jaraguá do Sul",
      "estado": "SC",
      "telefone_fixo": "(47) 2991-9298",
      "celular": "(47) 98408-2757",
      "altura": "1,84",
      "peso": 80,
      "tipo_sanguineo": "O-",
      "cor": "laranja"
    }
  ]
  
    
  

  return (
    <div className="App">
      <header>
        <h1>Lista de Pacientes</h1>
      </header>
      <table>
        <thead>
          <tr>
            <th>Nome</th>
            <th>CPF</th>
            <th>Email</th>
            <th>Celular</th>
          </tr>
        </thead>
        <tbody>
          {patients.map(patient => (
            <tr key={patient.CPF}>
              <td>
                <Link to={`/paciente/${patient.cpf}`}>{patient.nome}</Link>
              </td>
              <td>{patient.cpf}</td>
              <td>{patient.email}</td>
              <td>{patient.celular}</td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}

export default PacientesPage;
